# Generated by Django 2.0.5 on 2018-09-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tidder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueuser',
            name='username',
            field=models.CharField(default='username', max_length=20),
        ),
    ]
