# Generated by Django 2.0.5 on 2018-09-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tidder', '0002_uniqueuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueuser',
            name='city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='uniqueuser',
            name='username',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
