# Generated by Django 2.0.5 on 2018-09-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tidder', '0003_auto_20180915_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniqueuser',
            name='city',
        ),
        migrations.AddField(
            model_name='uniqueuser',
            name='country',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
