# Generated by Django 2.0.5 on 2018-09-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tidder', '0008_auto_20180915_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='posts',
        ),
    ]
